### PR TITLE
[WIP] Script Editor Improvements and Autocompletion

### PR DESCRIPTION
**Pull request by Squareys**
**Very early pull request for discussion!**

Hello @ctrueden, hello all, 

this will be where I will work on the script editor, make suggestions and discuss changes.
I didn't do too much so far and the main timeframe I am going to be working on this will be mid July - end of September. I'm guessing I might find some time before every now and then, though.

My suggestion on how to go about the main goal "Autocomplete for Java" would be:
 - [x] Add Javadoc to EditorPane (primarily to improve my own understanding of that specific class)
   - [x] Potentially pull apart EditorPane for readability/clarity, extract util methods etc.
 - [x] Add API for Autocompletion, SingletonService and Plugins based on https://github.com/bobbylight/AutoComplete
 - [x] Implement Autocompletion for Java (primarily) using https://github.com/bobbylight/RSTALanguageSupport (supports some other languages aswell)
   - [ ] Add some preferences and settings in the UI for more fine-grained control over indexing settings etc.

The focus on Java is related to my work on the ScriptingNode for KNIME-ImageProcessing.
Please tell me what you think and if you see any problems with that rough idea of a plan.

Regarding code format: would it be okay if I let eclipse code formatter run over the code (or the script package) once and commit that in a big "Format code" commit?

Greetings,
Squareys (Jonathan)

### CODE REVIEW

**Comment by ctrueden** [comment]
Thanks @Squareys, these changes are great. I cherry picked them both to master (with a small tweak on the `PrefService` one), so you can probably just do `git fetch origin && git reset --hard origin/master && git push --force` on this branch to start it over from the latest now.

**Comment by Squareys** [comment]
Well, this was not supposed to get closed.

**Comment by Squareys** [comment]
@ctrueden Changes up to and including https://github.com/Squareys/imagej-ui-swing/commit/4afa70069e5677f96224a302a931026e4d6c7381 ("Remove managed scijava-ui-swing version") could be already merged, if you want to.

Next feature will be autocompletion and will take a while to get somewhat stable.

**Comment by ctrueden** [comment]
@Squareys Thanks. Feel free to create a smaller topic branch with only those changes which are ready, then merge it to master. If no one on your side has commit rights, let me know and I'll add you ASAP.

**Comment by Squareys** [comment]
> then merge it to master

like *just merge* without review? (I have commit rights, I believe)

**Comment by Squareys** [comment]
I could at least point out one or two commits for you to look at more closely, just in cases where I'm not entirely sure if things were a certain way for a reason.

**Comment by hinerm** [comment]
@Squareys is there anything in this PR not covered by #51 and #54 ?

**Comment by Squareys** [comment]
Nope, both of them originated from this one. I created "topic-branches" for some cleaner pullrequest.
This can be closed as soon as they are both merged.

**Comment by ctrueden** [comment]
Thanks @Squareys!

**Pull request closed without merging**
