### PR TITLE
SitesDialog: fix appearing of previous URL

### PR DESCRIPTION
**Pull request by stelfrich**
Removing a row that was still edited from the manage update sites dialog resulted in validity checks which are actually unnecessary for a site that is removed and prohibited proper stopping of the editing process. This in turn resulted in the URL of a previous editing to reappear once you add a new update site.

### CODE REVIEW

**Comment by stelfrich** [comment]
Steps to reproduce the issue:

1. _Help > Update..._
2. _Manage update sites_
3. _Add update site_
4. Insert bogus URL (`abcde`)
5. _OK_
6. _Remove_
7. _Yes_
8. _Add update site_

Inserts a new update site with the bogus URL and shows an error message. Should, however, actually start with an empty row without errors.

**Comment by imagejan** [comment]
I just noticed that there's still/again a branch [`fix-remove-after-exception`](https://github.com/imagej/imagej-ui-swing/compare/master...fix-remove-after-exception).

@stelfrich it seems that you pushed after this PR was merged, right? Should the remaining changes (see link above) be merged as well?

**Comment by stelfrich** [comment]
Thanks for noticing @imagejan! I'll file a separate PR for the changes on that branch (which I haven't created by chance ;-))

**Comment by stelfrich** [comment]
Thanks for noticing, @imagejan! I have deleted the branch since I couldn't find any additional issues that this might have fixed (in a a long forgotten past...).

**Pull request merged**
